Update build-universal-ffmpeg.yml

diff --git a/.github/workflows/build-universal-ffmpeg.yml b/.github/workflows/build-universal-ffmpeg.yml
--- a/.github/workflows/build-universal-ffmpeg.yml
+++ b/.github/workflows/build-universal-ffmpeg.yml
@@ -14,9 +14,9 @@ jobs:
 
       - name: Download FFmpeg ARM (Apple Silicon)
         run: |
-          wget -qO ffmpeg-arm.zip https://www.videohelp.com/download/ffmpeg-9.0.2-macosarm-static.zip || { echo "Failed to download arm FFmpeg"; exit 1; }
-          unzip ffmpeg-arm.zip -d arm
-          mv arm/ffmpeg ffmpeg-arm
+          wget -qO ffmpeg-arm.tar.gz https://github.com/CSReviser/ffmpeg-build/releases/download/9.0.2/ffmpeg-macos-arm64.tar.gz || { echo "Failed to download arm FFmpeg"; exit 1; }
+          tar -xzvf ffmpeg-arm.tar.gz ffmpeg
+          mv ffmpeg ffmpeg-arm
           chmod +x ffmpeg-arm
           
 #          unzip ffmpeg-arm.zip -d arm
@@ -24,6 +24,7 @@ jobs:
 #          tar -xzvf ffmpeg-arm.tar.gz ffmpeg
 #          mv ffmpeg ffmpeg-arm
 #          wget -qO ffmpeg-arm.zip https://www.osxexperts.net/ffmpeg81arm.zip || { echo "Failed to download arm FFmpeg"; exit 1; }
+#          wget -qO ffmpeg-arm.zip https://www.videohelp.com/download/ffmpeg-9.0.2-macosarm-static.zip || { echo "Failed to download arm FFmpeg"; exit 1; }
 
       - name: Download FFmpeg Intel (x86_64)
         run: |
