Update build-universal-ffmpeg.yml

diff --git a/.github/workflows/build-universal-ffmpeg.yml b/.github/workflows/build-universal-ffmpeg.yml
--- a/.github/workflows/build-universal-ffmpeg.yml
+++ b/.github/workflows/build-universal-ffmpeg.yml
@@ -14,7 +14,7 @@ jobs:
 
       - name: Download FFmpeg ARM (Apple Silicon)
         run: |
-          wget -qO ffmpeg-arm.tar.gz https://github.com/CSReviser/ffmpeg-build/releases/download/9.0.1/ffmpeg-macos-arm64.tar.gz || { echo "Failed to download arm FFmpeg"; exit 1; }
+          wget -qO ffmpeg-arm.tar.gz https://github.com/CSReviser/ffmpeg-build/releases/download/9.0.2/ffmpeg-macos-arm64.tar.gz || { echo "Failed to download arm FFmpeg"; exit 1; }
           tar -xzvf ffmpeg-arm.tar.gz ffmpeg
           mv ffmpeg ffmpeg-arm
           chmod +x ffmpeg-arm
@@ -25,7 +25,7 @@ jobs:
 
       - name: Download FFmpeg Intel (x86_64)
         run: |
-          wget -qO ffmpeg-intel.7z https://evermeet.cx/ffmpeg/ffmpeg-9.0.1.7z || { echo "Failed to download FFmpeg-intel"; exit 1; }
+          wget -qO ffmpeg-intel.7z https://evermeet.cx/ffmpeg/ffmpeg-9.0.2.7z || { echo "Failed to download FFmpeg-intel"; exit 1; }
           7z x ffmpeg-intel.7z -offmpeg-intel
           mv ffmpeg-intel/ffmpeg ffmpeg-x86_64
           chmod +x ffmpeg-x86_64
