Update build-universal-ffmpeg.yml

diff --git a/.github/workflows/build-universal-ffmpeg.yml b/.github/workflows/build-universal-ffmpeg.yml
--- a/.github/workflows/build-universal-ffmpeg.yml
+++ b/.github/workflows/build-universal-ffmpeg.yml
@@ -14,18 +14,20 @@ jobs:
 
       - name: Download FFmpeg ARM (Apple Silicon)
         run: |
-          wget -qO ffmpeg-arm.tar.gz https://github.com/CSReviser/ffmpeg-build/releases/download/9.0.2/ffmpeg-macos-arm64.tar.gz || { echo "Failed to download arm FFmpeg"; exit 1; }
-          tar -xzvf ffmpeg-arm.tar.gz ffmpeg
-          mv ffmpeg ffmpeg-arm
+          wget -qO ffmpeg-arm.tar.gz https://www.osxexperts.net/ffmpeg9arm.zip || { echo "Failed to download arm FFmpeg"; exit 1; }
+          unzip ffmpeg-arm.zip -d arm
+          mv arm/ffmpeg ffmpeg-arm
           chmod +x ffmpeg-arm
           
 #          unzip ffmpeg-arm.zip -d arm
 #          mv arm/ffmpeg ffmpeg-arm
+#          tar -xzvf ffmpeg-arm.tar.gz ffmpeg
+#          mv ffmpeg ffmpeg-arm
 #          wget -qO ffmpeg-arm.zip https://www.osxexperts.net/ffmpeg81arm.zip || { echo "Failed to download arm FFmpeg"; exit 1; }
 
       - name: Download FFmpeg Intel (x86_64)
         run: |
-          wget -qO ffmpeg-intel.7z https://evermeet.cx/ffmpeg/ffmpeg-9.0.2.7z || { echo "Failed to download FFmpeg-intel"; exit 1; }
+          wget -qO ffmpeg-intel.7z https://evermeet.cx/ffmpeg/ffmpeg-9.0.7z || { echo "Failed to download FFmpeg-intel"; exit 1; }
           7z x ffmpeg-intel.7z -offmpeg-intel
           mv ffmpeg-intel/ffmpeg ffmpeg-x86_64
           chmod +x ffmpeg-x86_64
