Update FFmpeg download links and formats in workflow

diff --git a/.github/workflows/build-universal-ffmpeg.yml b/.github/workflows/build-universal-ffmpeg.yml
--- a/.github/workflows/build-universal-ffmpeg.yml
+++ b/.github/workflows/build-universal-ffmpeg.yml
@@ -14,18 +14,19 @@ jobs:
 
       - name: Download FFmpeg ARM (Apple Silicon)
         run: |
-          wget -qO ffmpeg-arm.zip https://www.osxexperts.net/ffmpeg9arm.zip || { echo "Failed to download arm FFmpeg"; exit 1; }
-          unzip ffmpeg-arm.zip -d arm
+          wget -qO ffmpeg-arm.tar.gz https://github.com/CSReviser/ffmpeg-build/releases/download/9.0.1/ffmpeg-macos-arm64.tar.gz || { echo "Failed to download arm FFmpeg"; exit 1; }
+          unzip ffmpeg-arm.tar.gz -d arm
           mv arm/ffmpeg ffmpeg-arm
           chmod +x ffmpeg-arm
 #          wget -qO ffmpeg-arm.zip https://www.osxexperts.net/ffmpeg81arm.zip || { echo "Failed to download arm FFmpeg"; exit 1; }
 
       - name: Download FFmpeg Intel (x86_64)
         run: |
-          wget -qO ffmpeg-intel.zip https://www.osxexperts.net/ffmpeg80intel.zip || { echo "Failed to download FFmpeg-intel"; exit 1; }
-          7z x ffmpeg-intel.zip -offmpeg-intel
+          wget -qO ffmpeg-intel.7z https://evermeet.cx/ffmpeg/ffmpeg-9.0.1.7z || { echo "Failed to download FFmpeg-intel"; exit 1; }
+          7z x ffmpeg-9.0.1.7z -offmpeg-intel
           mv ffmpeg-intel/ffmpeg ffmpeg-x86_64
           chmod +x ffmpeg-x86_64
+ #         wget -qO ffmpeg-intel.zip https://www.osxexperts.net/ffmpeg80intel.zip || { echo "Failed to download FFmpeg-intel"; exit 1; }
  #         wget -qO ffmpeg-intel.7z https://evermeet.cx/ffmpeg/ffmpeg-8.1.7z || { echo "Failed to download FFmpeg-intel"; exit 1; }
       - name: Verify architectures
         run: |
