Update FFmpeg download links for ARM and Intel

diff --git a/.github/workflows/build-universal-ffmpeg.yml b/.github/workflows/build-universal-ffmpeg.yml
--- a/.github/workflows/build-universal-ffmpeg.yml
+++ b/.github/workflows/build-universal-ffmpeg.yml
@@ -14,7 +14,7 @@ jobs:
 
       - name: Download FFmpeg ARM (Apple Silicon)
         run: |
-          wget -qO ffmpeg-arm.zip https://www.videohelp.com/download/ffmpeg-9.0-macosarm-static.zip || { echo "Failed to download arm FFmpeg"; exit 1; }
+          wget -qO ffmpeg-arm.zip https://www.osxexperts.net/ffmpeg9arm.zip || { echo "Failed to download arm FFmpeg"; exit 1; }
           unzip ffmpeg-arm.zip -d arm
           mv arm/ffmpeg ffmpeg-arm
           chmod +x ffmpeg-arm
@@ -22,8 +22,8 @@ jobs:
 
       - name: Download FFmpeg Intel (x86_64)
         run: |
-          wget -qO ffmpeg-intel.7z https://www.videohelp.com/download/ffmpeg-9.0-macos64-static.7z || { echo "Failed to download FFmpeg-intel"; exit 1; }
-          7z x ffmpeg-intel.7z -offmpeg-intel
+          wget -qO ffmpeg-intel.zip https://www.osxexperts.net/ffmpeg80intel.zip || { echo "Failed to download FFmpeg-intel"; exit 1; }
+          7z x ffmpeg-intel.zip -offmpeg-intel
           mv ffmpeg-intel/ffmpeg ffmpeg-x86_64
           chmod +x ffmpeg-x86_64
  #         wget -qO ffmpeg-intel.7z https://evermeet.cx/ffmpeg/ffmpeg-8.1.7z || { echo "Failed to download FFmpeg-intel"; exit 1; }
